version: "3.8"

services:
  notes:
    container_name: app-notes-mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/patientnotes
    build: ./
    ports:
      - "8082:8082"
    restart: always
    networks:
      - app-network  # Use the same network as the other services
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: patientnotes
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network: {}
