version: "3.8"
services:
  notes:
    container_name: app-notes-mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/patientnotes
    build: ./
    ports:
      - "8082:8082"
    restart: always
    networks:
      - mongodb_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: patientnotes
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mongodb_network

volumes:
  data: {}

networks:
  mongodb_network: {}  # Explicitly define the network here